#!/usr/bin/env python3
"""Generate src/fpga/core/s32x_msg_rom.sv: the font and text ROMs for the core's on-screen
messages (currently the missing-BIOS screen). The 5x7 font below was drawn for this project.

Text screen: 32 columns x 28 rows of 8x8 cells (fits H32, 256x224). Each cell holds a 6-bit
character code; code 0 is a space. Row attributes (color) are chosen in core_top.v."""
from pathlib import Path

GLYPHS = {
    ' ': ["     "] * 7,
    'A': [" ### ", "#   #", "#   #", "#####", "#   #", "#   #", "#   #"],
    'B': ["#### ", "#   #", "#   #", "#### ", "#   #", "#   #", "#### "],
    'C': [" ### ", "#   #", "#    ", "#    ", "#    ", "#   #", " ### "],
    'D': ["#### ", "#   #", "#   #", "#   #", "#   #", "#   #", "#### "],
    'E': ["#####", "#    ", "#    ", "#### ", "#    ", "#    ", "#####"],
    'F': ["#####", "#    ", "#    ", "#### ", "#    ", "#    ", "#    "],
    'G': [" ### ", "#   #", "#    ", "# ###", "#   #", "#   #", " ####"],
    'H': ["#   #", "#   #", "#   #", "#####", "#   #", "#   #", "#   #"],
    'I': [" ### ", "  #  ", "  #  ", "  #  ", "  #  ", "  #  ", " ### "],
    'J': ["  ###", "   # ", "   # ", "   # ", "   # ", "#  # ", " ##  "],
    'K': ["#   #", "#  # ", "# #  ", "##   ", "# #  ", "#  # ", "#   #"],
    'L': ["#    ", "#    ", "#    ", "#    ", "#    ", "#    ", "#####"],
    'M': ["#   #", "## ##", "# # #", "# # #", "#   #", "#   #", "#   #"],
    'N': ["#   #", "##  #", "# # #", "#  ##", "#   #", "#   #", "#   #"],
    'O': [" ### ", "#   #", "#   #", "#   #", "#   #", "#   #", " ### "],
    'P': ["#### ", "#   #", "#   #", "#### ", "#    ", "#    ", "#    "],
    'Q': [" ### ", "#   #", "#   #", "#   #", "# # #", "#  # ", " ## #"],
    'R': ["#### ", "#   #", "#   #", "#### ", "# #  ", "#  # ", "#   #"],
    'S': [" ####", "#    ", "#    ", " ### ", "    #", "    #", "#### "],
    'T': ["#####", "  #  ", "  #  ", "  #  ", "  #  ", "  #  ", "  #  "],
    'U': ["#   #", "#   #", "#   #", "#   #", "#   #", "#   #", " ### "],
    'V': ["#   #", "#   #", "#   #", "#   #", "#   #", " # # ", "  #  "],
    'W': ["#   #", "#   #", "#   #", "# # #", "# # #", "## ##", "#   #"],
    'X': ["#   #", "#   #", " # # ", "  #  ", " # # ", "#   #", "#   #"],
    'Y': ["#   #", "#   #", " # # ", "  #  ", "  #  ", "  #  ", "  #  "],
    'Z': ["#####", "    #", "   # ", "  #  ", " #   ", "#    ", "#####"],
    '0': [" ### ", "#   #", "#  ##", "# # #", "##  #", "#   #", " ### "],
    '1': ["  #  ", " ##  ", "  #  ", "  #  ", "  #  ", "  #  ", " ### "],
    '2': [" ### ", "#   #", "    #", "   # ", "  #  ", " #   ", "#####"],
    '3': ["#####", "   # ", "  #  ", "   # ", "    #", "#   #", " ### "],
    '4': ["   # ", "  ## ", " # # ", "#  # ", "#####", "   # ", "   # "],
    '5': ["#####", "#    ", "#### ", "    #", "    #", "#   #", " ### "],
    '6': ["  ## ", " #   ", "#    ", "#### ", "#   #", "#   #", " ### "],
    '7': ["#####", "    #", "   # ", "  #  ", " #   ", " #   ", " #   "],
    '8': [" ### ", "#   #", "#   #", " ### ", "#   #", "#   #", " ### "],
    '9': [" ### ", "#   #", "#   #", " ####", "    #", "   # ", " ##  "],
    '/': ["    #", "    #", "   # ", "  #  ", " #   ", "#    ", "#    "],
    '_': ["     ", "     ", "     ", "     ", "     ", "     ", "#####"],
    '.': ["     ", "     ", "     ", "     ", "     ", " ##  ", " ##  "],
    ',': ["     ", "     ", "     ", "     ", " ##  ", "  #  ", " #   "],
    '-': ["     ", "     ", "     ", "#####", "     ", "     ", "     "],
    ':': ["     ", " ##  ", " ##  ", "     ", " ##  ", " ##  ", "     "],
    '=': ["     ", "     ", "#####", "     ", "#####", "     ", "     "],
}
CODES = {c: i for i, c in enumerate(GLYPHS)}          # ' ' = 0
assert len(CODES) <= 64

COLS, ROWS = 32, 28
# (row, text). Rows 14-16 are the three BIOS files; core_top colors them found/missing.
TEXT = [
    (8,  "32X BIOS FILE MISSING"),
    (10, "COPY THE 32X BIOS FILES TO"),
    (11, "ASSETS/32X/COMMON/ ON THE"),
    (12, "SD CARD:"),
    (14, "32X_G_BIOS.BIN  68K"),
    (15, "32X_M_BIOS.BIN  MASTER SH-2"),
    (16, "32X_S_BIOS.BIN  SLAVE SH-2"),
    (18, "GREEN = FOUND, RED = MISSING"),
]


def main():
    font = [0] * (64 * 8)
    for c, rows in GLYPHS.items():
        assert len(rows) == 7 and all(len(r) == 5 for r in rows), c
        for y, r in enumerate(rows):
            # 8-pixel cell: 1 column left margin, 5 glyph columns, 2 right; bit 7 = leftmost
            font[CODES[c] * 8 + y] = sum(1 << (6 - x) for x, p in enumerate(r) if p == '#')
    text = [0] * 1024
    for row, t in TEXT:
        assert len(t) <= COLS - 2, t
        for x, c in enumerate(t):
            text[row * COLS + 2 + x] = CODES[c]          # two-cell left margin

    out = ["// Generated by tools/gen_msg_rom.py: do not edit. Font drawn for this project.",
           "module s32x_msg_rom (",
           "\tinput            clk,",
           "\tinput      [9:0] text_addr,   // {row[4:0], col[4:0]}",
           "\toutput reg [5:0] text_q,",
           "\tinput      [8:0] font_addr,   // {char[5:0], line[2:0]}",
           "\toutput reg [7:0] font_q       // bit 7 = leftmost pixel",
           ");",
           "",
           "reg [5:0] text_rom[1024];",
           "reg [7:0] font_rom[512];",
           "initial begin"]
    out += [f"\ttext_rom[{i}] = 6'd{v};" for i, v in enumerate(text)]
    out += [f"\tfont_rom[{i}] = 8'h{v:02X};" for i, v in enumerate(font)]
    out += ["end",
            "",
            "always @(posedge clk) begin",
            "\ttext_q <= text_rom[text_addr];",
            "\tfont_q <= font_rom[font_addr];",
            "end",
            "",
            "endmodule",
            ""]
    p = Path(__file__).resolve().parent.parent / "src/fpga/core/s32x_msg_rom.sv"
    p.write_text("\n".join(out))
    print(f"wrote {p}")


if __name__ == "__main__":
    main()
